In [1]:
import pandas as pd
df = pd.read_csv("../data/raw/financial_fraud_detection_dataset.csv")
df.head()

,transaction_id,timestamp,sender_account,receiver_account,amount,transaction_type,merchant_category,location,device_used,is_fraud,fraud_type,time_since_last_transaction,spending_deviation_score,velocity_score,geo_anomaly_score,payment_channel,ip_address,device_hash
0,T100000,2023-08-22T09:22:43.516168,ACC877572,ACC388389,343.78,withdrawal,utilities,Tokyo,mobile,False,NaN,NaN,-0.21,3,0.22,card,13.101.214.112,D8536477
1,T100001,2023-08-04T01:58:02.606711,ACC895667,ACC944962,419.65,withdrawal,online,Toronto,atm,False,NaN,NaN,-0.14,7,0.96,ACH,172.52.47.194,D2622631
2,T100002,2023-05-12T11:39:33.742963,ACC733052,ACC377370,2773.86,deposit,other,London,pos,False,NaN,NaN,-1.78,20,0.89,card,185.98.35.23,D4823498
3,T100003,2023-10-10T06:04:43.195112,ACC996865,ACC344098,1666.22,deposit,online,Sydney,pos,False,NaN,NaN,-0.60,6,0.37,wire_transfer,107.136.36.87,D9961380
4,T100004,2023-09-24T08:09:02.700162,ACC584714,ACC497887,24.43,transfer,utilities,Toronto,mobile,False,NaN,NaN,0.79,13,0.27,ACH,108.161.108.255,D7637601

In [3]:
df.shape

(5000000, 18)

In [4]:
df.columns.tolist()

['transaction_id',
 'timestamp',
 'sender_account',
 'receiver_account',
 'amount',
 'transaction_type',
 'merchant_category',
 'location',
 'device_used',
 'is_fraud',
 'fraud_type',
 'time_since_last_transaction',
 'spending_deviation_score',
 'velocity_score',
 'geo_anomaly_score',
 'payment_channel',
 'ip_address',
 'device_hash']

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000000 entries, 0 to 4999999
Data columns (total 18 columns):
 #   Column                       Dtype
---  ------                       -----
 0   transaction_id               object
 1   timestamp                    object
 2   sender_account               object
 3   receiver_account             object
 4   amount                       float64
 5   transaction_type             object
 6   merchant_category            object
 7   location                     object
 8   device_used                  object
 9   is_fraud                     bool
 10  fraud_type                   object
 11  time_since_last_transaction  float64
 12  spending_deviation_score     float64
 13  velocity_score               int64
 14  geo_anomaly_score            float64
 15  payment_channel              object
 16  ip_address                   object
 17  device_hash                  object
dtypes: bool(1), float64(4), int64(1), object(12)
memory usage: 653.3+ MB

In [6]:
df.isnull().sum()

transaction_id                       0
timestamp                            0
sender_account                       0
receiver_account                     0
amount                               0
transaction_type                     0
merchant_category                    0
location                             0
device_used                          0
is_fraud                             0
fraud_type                     4820447
time_since_last_transaction     896513
spending_deviation_score             0
velocity_score                       0
geo_anomaly_score                    0
payment_channel                      0
ip_address                           0
device_hash                          0
dtype: int64

In [7]:
df["column_name"].value_counts()

KeyError: 'column_name'

In [8]:
df["is_fraud"].value_counts()

is_fraud
False    4820447
True      179553
Name: count, dtype: int64

In [ ]:

df["merchant_category"].value_counts()

merchant_category
retail           626319
travel           625656
restaurant       625483
entertainment    625332
grocery          624954
other            624589
utilities        624086
online           623581
Name: count, dtype: int64

In [10]:
df["transaction_type"].value_counts()

transaction_type
deposit       1250593
payment       1250438
transfer      1250334
withdrawal    1248635
Name: count, dtype: int64

In [11]:
df["payment_channel"].value_counts()

payment_channel
wire_transfer    1251219
ACH              1250241
card             1249693
UPI              1248847
Name: count, dtype: int64

In [12]:
df["device_used"].value_counts()

device_used
mobile    1251131
web       1250071
atm       1249640
pos       1249158
Name: count, dtype: int64

In [13]:
df["location"].value_counts().head(20)

location
Tokyo        625994
New York     625354
Singapore    625313
Berlin       625289
Sydney       625125
Toronto      624349
Dubai        624320
London       624256
Name: count, dtype: int64

In [14]:
df["fraud_type"].value_counts(dropna=False)

fraud_type
NaN                 4820447
card_not_present     179553
Name: count, dtype: int64

In [15]:
df[df["time_since_last_transaction"].isnull()].head()

,transaction_id,timestamp,sender_account,receiver_account,amount,transaction_type,merchant_category,location,device_used,is_fraud,fraud_type,time_since_last_transaction,spending_deviation_score,velocity_score,geo_anomaly_score,payment_channel,ip_address,device_hash
0,T100000,2023-08-22T09:22:43.516168,ACC877572,ACC388389,343.78,withdrawal,utilities,Tokyo,mobile,False,NaN,NaN,-0.21,3,0.22,card,13.101.214.112,D8536477
1,T100001,2023-08-04T01:58:02.606711,ACC895667,ACC944962,419.65,withdrawal,online,Toronto,atm,False,NaN,NaN,-0.14,7,0.96,ACH,172.52.47.194,D2622631
2,T100002,2023-05-12T11:39:33.742963,ACC733052,ACC377370,2773.86,deposit,other,London,pos,False,NaN,NaN,-1.78,20,0.89,card,185.98.35.23,D4823498
3,T100003,2023-10-10T06:04:43.195112,ACC996865,ACC344098,1666.22,deposit,online,Sydney,pos,False,NaN,NaN,-0.60,6,0.37,wire_transfer,107.136.36.87,D9961380
4,T100004,2023-09-24T08:09:02.700162,ACC584714,ACC497887,24.43,transfer,utilities,Toronto,mobile,False,NaN,NaN,0.79,13,0.27,ACH,108.161.108.255,D7637601

In [16]:
df["time_since_last_transaction"].describe()

count    4.103487e+06
mean     1.525799e+00
std      3.576569e+03
min     -8.777814e+03
25%     -2.562376e+03
50%      8.442747e-01
75%      2.568339e+03
max      8.757758e+03
Name: time_since_last_transaction, dtype: float64

In [17]:
df[["time_since_last_transaction",
    "spending_deviation_score",
    "velocity_score",
    "geo_anomaly_score"]].describe()

,time_since_last_transaction,spending_deviation_score,velocity_score,geo_anomaly_score
count,4.103487e+06,5.000000e+06,5.000000e+06,5.000000e+06
mean,1.525799e+00,-3.881160e-04,1.050132e+01,5.000293e-01
std,3.576569e+03,1.000807e+00,5.766842e+00,2.886349e-01
min,-8.777814e+03,-5.260000e+00,1.000000e+00,0.000000e+00
25%,-2.562376e+03,-6.800000e-01,5.000000e+00,2.500000e-01
50%,8.442747e-01,0.000000e+00,1.100000e+01,5.000000e-01
75%,2.568339e+03,6.700000e-01,1.600000e+01,7.500000e-01
max,8.757758e+03,5.020000e+00,2.000000e+01,1.000000e+00

In [18]:
df["timestamp"].head()

0    2023-08-22T09:22:43.516168
1    2023-08-04T01:58:02.606711
2    2023-05-12T11:39:33.742963
3    2023-10-10T06:04:43.195112
4    2023-09-24T08:09:02.700162
Name: timestamp, dtype: object

In [24]:
df["timestamp"] = pd.to_datetime(
    df["timestamp"],
    format="mixed"
)

In [25]:
df["timestamp"] = pd.to_datetime(
    df["timestamp"],
    format="mixed",
    errors="coerce"
)

In [26]:
df["timestamp"].isna().sum()

np.int64(0)

In [27]:
df["hour"] = df["timestamp"].dt.hour
df["day_of_week"] = df["timestamp"].dt.dayofweek
df["month"] = df["timestamp"].dt.month
df["is_weekend"] = (df["day_of_week"] >= 5).astype(int)

In [28]:
df[[
    "timestamp",
    "hour",
    "day_of_week",
    "month",
    "is_weekend"
]].head()

                   timestamp  hour  day_of_week  month  is_weekend
0 2023-08-22 09:22:43.516168     9            1      8           0
1 2023-08-04 01:58:02.606711     1            4      8           0
2 2023-05-12 11:39:33.742963    11            4      5           0
3 2023-10-10 06:04:43.195112     6            1     10           0
4 2023-09-24 08:09:02.700162     8            6      9           1